'use client';
import {useEffect,useMemo,useState} from 'react';
import {Search,ShoppingBag,ArrowRight,Minus,Plus,Package,Check,Loader2} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
const requestKey=()=>Array.from(crypto.getRandomValues(new Uint8Array(20)),b=>b.toString(16).padStart(2,'0')).join('');
export const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
export const unit=(s:string)=>({dozen:'dozen (12 pieces)',displayPack:'display pack',pack:'pack',each:'each',case:'case'}[s]||'unit to confirm');
export async function api(path:string,data?:any):Promise<any>{const r=await fetch('/api/commerce/'+path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{cache:'no-store'});const j:any=await r.json();if(!r.ok)throw new Error(j.error||'Unable to complete this action.');return j;}
export default function Catalog({mode,user}:{mode:'public'|'sales',user?:any}){const sales=mode==='sales';const [products,setProducts]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState('All'),[sort,setSort]=useState('code'),[page,setPage]=useState(1),[cart,setCart]=useState<Record<string,number>>({}),[open,setOpen]=useState(false),[customerId,setCustomerId]=useState(''),[customerSearch,setCustomerSearch]=useState(''),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[confirmation,setConfirmation]=useState(''),[requestId,setRequestId]=useState(''),[address,setAddress]=useState({name:'',email:'',phone:'',line1:'',line2:'',city:'',region:'',postal:'',country:'US'});
function load(){setLoading(true);setError('');Promise.all([api(sales?'staff-products':'products'),sales?api('customers'):Promise.resolve({customers:[]})]).then(([p,c])=>{setProducts(p.products);setCustomers(c.customers);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));}
useEffect(()=>{load();setRequestId(requestKey());},[]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'search_catalog',description:'Set the visible catalog search to an item number or description. Does not create an order.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(typeof input?.query!=='string'||input.query.length>200)throw new Error('Enter a search query of at most 200 characters.');setSearch(input.query);setCategory('All');setPage(1);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {query:input.query};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
const categories=useMemo(()=>['All',...Array.from(new Set(products.map(p=>p.category))).sort()], [products]);
const filtered=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&`${p.code} ${p.name} ${p.description}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='price'?(a.price??Infinity)-(b.price??Infinity):a.code.localeCompare(b.code,undefined,{numeric:true})),[products,search,category,sort]);
const lines=products.filter(p=>cart[p.id]).map(p=>({...p,qty:cart[p.id]}));const total=lines.reduce((sum,p)=>sum+(p.price||0)*p.qty,0);const count=lines.reduce((s,p)=>s+p.qty,0);
function qty(id:string,n:number){setCart(c=>{const next={...c};if(n<=0)delete next[id];else next[id]=Math.min(10000,n);return next;});setConfirmation('');}
function selectCustomer(id:string){setCustomerId(id);const c=customers.find(c=>c.id===id);if(c){let a:any={};try{a=JSON.parse(c.address);}catch{}setAddress({...address,name:c.name,email:c.email,phone:c.phone,line1:a.Line1||'',line2:a.Line2||'',city:a.City||'',region:a.CountrySubDivisionCode||'',postal:a.PostalCode||'',country:a.Country||'US'});}}
async function submit(e:any){e.preventDefault();setError('');setBusy(true);try{if(!sales)throw new Error('Online checkout is not available yet. No payment was taken.');const r=await api('orders',{requestId,customerId,lines:lines.map(p=>({id:p.id,qty:p.qty,price:p.price})),address,notes});setConfirmation(r.id);setCart({});setRequestId(requestKey());}catch(e:any){setError(e.message);}finally{setBusy(false);}}
const field=(key:string,label:string,required=true,type='text')=><label key={key}>{label}<input required={required} type={type} autoComplete={key==='line1'?'address-line1':undefined} value={(address as any)[key]} onChange={e=>setAddress({...address,[key]:e.target.value})}/></label>;
return <><header className="topbar"><a href={sales?'/sales':'/'} className="brand"><span className="brandmark">2J</span><span><b>2J Group</b><small>{sales?'Sales portal':'Beauty & everyday essentials'}</small></span></a><div className="headlinks">{sales?<><span className="staffname">{user?.email}</span>{['owner','office'].includes(user?.role)&&<a href="/admin">Office</a>}<a href="/sales/orders">My orders</a><a href="/">Public store</a></>:<a href="/sales">Staff sign in</a>}<button className="dark" onClick={()=>setOpen(true)}><ShoppingBag size={18}/>{sales?'Order':'Bag'} <span>{count}</span></button></div></header>
<main className="store"><section className="heading"><div><p className="eyebrow">{sales?'FOR APPROVED SALES STAFF':'THE 2J COLLECTION'}</p><h1>{sales?'Build a shop order.':'Beauty, by the dozen.'}</h1><p>{sales?'Select a QuickBooks customer, find the item, and send the order to your office.':'Explore beauty supplies and accessories. Check each item’s selling unit before adding it to your bag.'}</p></div><div className="headingnote"><Package size={24}/><span>{sales?'One catalog. Current prices.':'Same listed prices and pack sizes.'}<small>{sales?'Only approved items can be ordered.':'Online checkout is coming soon.'}</small></span></div></section>
{!sales&&<div className="notice">You can browse now. Prices appear after product review. Online ordering opens when payment and delivery settings are ready.</div>}
{error&&<div role="alert" className="error">{error} <button onClick={load}>Reload</button></div>}
<section className="catalogcontrols"><div className="searchbox"><Search size={21}/><input aria-label="Search item number or description" placeholder="Search item number or description" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div><label className="selectlabel">Category<select value={category} onChange={e=>{setCategory(e.target.value);setPage(1);}}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="selectlabel">Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="code">Item number</option><option value="price">Price: low to high</option></select></label></section>
<nav className="categories" aria-label="Popular categories">{['All','MM','BNO','CA','CB','E','HR','J','HB'].map(c=><button key={c} className={category===c?'selected':''} onClick={()=>{setCategory(c);setPage(1);}}>{c==='All'?'All products':c}</button>)}</nav>
<div className="resultline"><h2>{category==='All'?'Product catalog':`${category} collection`}</h2><span>{loading?'Loading catalog…':`${filtered.length.toLocaleString()} items`}</span></div>
{loading?<div className="empty"><Loader2 className="spin"/><p>Loading your catalog…</p></div>:!filtered.length?<div className="empty"><Search/><h3>No matching items</h3><p>Try an item number or a different category.</p><button onClick={()=>{setCategory('All');setSearch('');}}>Clear filters</button></div>:<section className="productgrid">{filtered.slice((page-1)*24,page*24).map(p=><article className="product" key={p.id}><div className="photo">{p.image?<img src={p.image} loading="lazy" alt={`${p.code} product photo`}/>:<div className="empty"><Package/><span>Photo awaiting match</span></div>}<span className="categorycode">{p.category||'Item'}</span></div><div className="producttext"><div className="productcode">{p.code}</div><h3>{p.name!==p.code?p.name:p.description?.split('.')[0]||'Catalog item'}</h3><p className="description">{p.description||'Description awaiting review.'}</p><details className="productdetails"><summary>Product details</summary><p>{p.description||'Description awaiting review.'}</p><p>Selling unit: {unit(p.unit)}</p></details><div className="price">{p.price!==null?<>{money(p.price)} <small>/ {unit(p.unit)}</small></>:<span className="pending">Price awaiting confirmation</span>}</div><button className={p.canOrder?'add':'unavailable'} disabled={!p.canOrder} onClick={()=>qty(p.id,(cart[p.id]||0)+1)}>{p.canOrder?<><Plus size={17}/>{cart[p.id]?`${cart[p.id]} in ${sales?'order':'bag'} · Add one`:`Add to ${sales?'order':'bag'}`}</>:'Not available to order'}</button></div></article>)}</section>}
{filtered.length>24&&<div className="pagination"><button disabled={page===1} onClick={()=>{setPage(page-1);window.scrollTo({top:250,behavior:'smooth'});}}>Previous</button><span>{page} / {Math.ceil(filtered.length/24)}</span><button disabled={page*24>=filtered.length} onClick={()=>{setPage(page+1);window.scrollTo({top:250,behavior:'smooth'});}}>Next</button></div>}
<footer><span>2J Group</span><p>{sales?'Orders reach the shared office queue. Invoice creation remains with the office.':'Check the listed quantity: each, dozen, pack, display pack or case.'}</p><a href="/sales">Staff access</a></footer></main>
<Sheet open={open} onOpenChange={setOpen}><SheetContent className="orderdrawer"><SheetHeader><SheetTitle>{sales?'Create a customer order':'Your shopping bag'}</SheetTitle><SheetDescription>{sales?'Orders are saved for office review.':'Checkout will open after payment setup.'}</SheetDescription></SheetHeader><div className="drawerbody">{confirmation?<div className="success"><Check/><h2>Order saved</h2><strong>{confirmation}</strong><p>Your office can now open this order. This is not a QuickBooks invoice.</p><a href="/sales/orders">View my orders</a></div>:<form onSubmit={submit}>
{sales&&<section className="formsection"><h3>QuickBooks customer</h3><input aria-label="Find customer" placeholder="Search customers" value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)}/><select required value={customerId} onChange={e=>selectCustomer(e.target.value)}><option value="">Select a customer</option>{customers.filter(c=>c.name.toLowerCase().includes(customerSearch.toLowerCase())).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{!customers.length&&<p className="hint">No customers imported yet. The owner needs to connect QuickBooks.</p>}</section>}
<section className="formsection"><h3>{sales?'Order items':'Bag items'}</h3>{!lines.length?<p className="hint">Your {sales?'order':'bag'} is empty. Add an approved item from the catalog.</p>:lines.map(p=><div className="cartline" key={p.id}><img src={p.image} alt=""/><div><b>{p.code}</b><small>{money(p.price)} / {unit(p.unit)}</small><div className="quantity"><button type="button" aria-label={`Decrease ${p.code}`} onClick={()=>qty(p.id,p.qty-1)}><Minus size={14}/></button><span>{p.qty}</span><button type="button" aria-label={`Increase ${p.code}`} onClick={()=>qty(p.id,p.qty+1)}><Plus size={14}/></button></div></div><strong>{money(p.price*p.qty)}</strong></div>)}</section>
<section className="formsection"><h3>Delivery details</h3>{field('name','Contact name')}{field('email','Email',true,'email')}{field('phone','Phone',false,'tel')}{field('line1','Street address')}{field('line2','Apartment / suite',false)}<div className="fieldpair">{field('city','City')}{field('region','State / region')}</div><div className="fieldpair">{field('postal','ZIP / postal code')}{field('country','Country')}</div><label>Order notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3}/></label></section><div className="subtotal"><span>Product subtotal</span><strong>{money(total)}</strong></div><p className="hint">Tax, delivery charges and availability require confirmation.</p>{error&&<p role="alert" className="error">{error}</p>}<button className="dark full" disabled={busy||!lines.length||!sales} type="submit">{busy?'Saving…':sales?'Send to office':'Online checkout unavailable'}<ArrowRight size={18}/></button>{!sales&&<p className="hint">No payment details are collected. No order is placed until checkout becomes available.</p>}</form>}</div></SheetContent></Sheet>
</>;
}
