'use client';
import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api,money,unit} from '../catalog';
export default function Admin({owner}:{owner:boolean}){const [data,setData]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[q,setQ]=useState(''),[editing,setEditing]=useState<any>(null),[view,setView]=useState<any>(null),[email,setEmail]=useState(''),[role,setRole]=useState('sales');
async function load(){try{setData(await api('admin'));}catch(e:any){setError(e.message);}}useEffect(()=>{load();},[]);
async function action(path:string,payload:any={}){setBusy(true);setError('');setMessage('');try{const r=await api(path,payload);if(r.url){window.location.assign(r.url);return;}setMessage(r.message||'Saved.');setEditing(null);await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
if(!data)return <main className="access"><h1>2J Office</h1><p>{error||'Loading shared records…'}</p><button onClick={load}>Try again</button></main>;
const matches=data.products.filter((p:any)=>`${p.code} ${p.name} ${p.match_status}`.toLowerCase().includes(q.toLowerCase())).slice(0,100);
return <><header className="topbar"><a className="brand" href="/sales"><span className="brandmark">2J</span><b>Office desk</b></a><div className="headlinks"><a href="/sales">Sales portal</a><a href="/">Public store</a><a href="/signout-with-chatgpt?return_to=/">Sign out</a></div></header><main className="office"><p className="eyebrow">2J GROUP OPERATIONS</p><h1>Catalog, customers & orders</h1><p className="introtext">Approve product matches once for both sites. Keep customer records inside the staff portal.</p>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}
<Tabs defaultValue="setup"><TabsList className="officeTabs"><TabsTrigger value="setup">Connections</TabsTrigger><TabsTrigger value="products">Product review</TabsTrigger><TabsTrigger value="orders">Office orders ({data.orders.length})</TabsTrigger>{owner&&<TabsTrigger value="access">Staff access</TabsTrigger>}</TabsList>
<TabsContent value="setup"><div className="connectionrow"><div><h2>QuickBooks Online</h2><p>{data.status.qboConnected?'Connected · '+data.status.environment:'Not connected'}</p><p className="hint">Imports products, prices, descriptions and existing customers.</p>{!data.status.qboConfigured&&<p className="hint">Intuit application credentials and secure token storage must be configured before the owner can authorize this connection.</p>}</div><div className="stackbuttons"><button disabled={busy||!data.status.qboConfigured} onClick={()=>action('qbo/connect')}>Connect QuickBooks</button><button className="dark" disabled={busy||!data.status.qboConnected} onClick={()=>action('sync')}>{busy?'Working…':'Import latest items & customers'}</button><small>Last complete import: {data.status.lastSync?new Date(data.status.lastSync).toLocaleString():'Not yet imported'}</small></div></div><div className="connectionrow"><div><h2>Drive catalog photos</h2><p>{data.status.photoCount.toLocaleString()} existing catalog records</p><p className="hint">Exact item-number matching. Review missing or duplicate matches before approving an item.</p><p className="hint">This is the imported catalog snapshot. Automatic Drive changes are not connected yet.</p></div><button disabled={busy} onClick={()=>action('seed')}>Load catalog for review</button></div><div className="connectionrow"><div><h2>Public payments & delivery</h2><p>Provider decision pending</p><p className="hint">Online checkout remains disabled. Before launch, choose the payment provider, shipping destinations, shipping charges and tax setup.</p></div><span className="statuslabel">Not taking payments</span></div></TabsContent>
<TabsContent value="products"><div className="reviewintro"><h2>Photo and selling-unit review</h2><p>QuickBooks supplies the price and description. Confirm the photo and selling unit before making the product orderable.</p><input aria-label="Search review items" placeholder="Search item number, description or match status" value={q} onChange={e=>setQ(e.target.value)}/><small>Showing up to 100 matching items. Search to find a specific code.</small></div><div className="tablewrap"><table><thead><tr><th>Photo</th><th>Item</th><th>Match</th><th>Price / unit</th><th>Visibility</th><th/></tr></thead><tbody>{matches.map((p:any)=><tr key={p.id}><td>{p.image&&<img className="thumb" src={p.image} alt={p.code}/>}</td><td><b>{p.code}</b><small>{p.name}</small></td><td>{p.match_status.replaceAll('_',' ')}</td><td>{p.price===null?'Awaiting review':money(p.price)}<small>{unit(p.unit)}</small></td><td>{p.approved?'Orderable':'Review needed'}</td><td><button onClick={()=>setEditing({...p,photoCode:''})}>Review</button></td></tr>)}</tbody></table></div></TabsContent>
<TabsContent value="orders"><h2>Shared office queue</h2><p>Saved sales orders appear here. QuickBooks invoicing and automated office emails are not enabled.</p>{!data.orders.length?<div className="empty"><h3>No orders yet</h3><p>Once products and customers are imported, salespeople can submit orders here.</p></div>:<div className="tablewrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Salesperson</th><th>Subtotal</th><th>Status</th><th/></tr></thead><tbody>{data.orders.map((o:any)=><tr key={o.id}><td>{o.id}<small>{new Date(o.created_at).toLocaleString()}</small></td><td>{o.customer_name}</td><td>{o.salesperson}</td><td>{money(o.subtotal)}</td><td>{o.status.replaceAll('_',' ')}</td><td><button onClick={()=>setView(o)}>Open</button></td></tr>)}</tbody></table></div>}</TabsContent>
{owner&&<TabsContent value="access"><h2>Approved staff</h2><p>Access uses individual ChatGPT sign-in. Adding an email authorizes that account without sending an invitation.</p><form className="accessform" onSubmit={e=>{e.preventDefault();action('staff',{email,role,active:true});}}><label>Staff email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="sales">Salesperson</option><option value="office">Office</option></select></label><button disabled={busy} className="dark">Approve access</button></form><div className="tablewrap"><table><thead><tr><th>Email</th><th>Role</th><th>Status</th><th/></tr></thead><tbody>{data.staff.map((s:any)=><tr key={s.email}><td>{s.email}</td><td>{s.role}</td><td>{s.active?'Active':'Removed'}</td><td><button disabled={busy} onClick={()=>action('staff',{...s,active:!s.active})}>{s.active?'Remove access':'Restore access'}</button></td></tr>)}</tbody></table></div><p className="hint">Owner access stays active. Salespeople can submit orders and see their own orders. Office staff can review all orders and edit product details.</p></TabsContent>}
</Tabs></main>
<Dialog open={!!editing} onOpenChange={o=>{if(!o)setEditing(null);}}><DialogContent className="reviewdialog"><DialogHeader><DialogTitle>Review {editing?.code}</DialogTitle><DialogDescription>Confirm the product photo and selling unit. QuickBooks owns the price.</DialogDescription></DialogHeader>{editing&&<form onSubmit={e=>{e.preventDefault();action('product',editing);}}>{editing.image&&<img className="reviewphoto" src={editing.image} alt={editing.code}/>}<label>Drive photo item code (optional correction)<input value={editing.photoCode} onChange={e=>setEditing({...editing,photoCode:e.target.value})}/></label><label>Description<textarea rows={3} value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>Selling unit<select required value={editing.unit} onChange={e=>setEditing({...editing,unit:e.target.value})}><option value="">Choose unit</option>{['each','dozen','pack','displayPack','case'].map(u=><option key={u} value={u}>{unit(u)}</option>)}</select></label><label className="checkbox"><input type="checkbox" checked={!!editing.approved} onChange={e=>setEditing({...editing,approved:e.target.checked})}/>I verified the photo, QuickBooks price and selling unit</label><button disabled={busy} className="dark full">Save for both sites</button></form>}</DialogContent></Dialog>
<Dialog open={!!view} onOpenChange={o=>{if(!o)setView(null);}}><DialogContent className="reviewdialog"><DialogHeader><DialogTitle>{view?.id}</DialogTitle><DialogDescription>Office review of a saved sales order</DialogDescription></DialogHeader>{view&&<><b>{view.customer_name}</b><pre>{JSON.stringify(JSON.parse(view.address),null,2)}</pre><div className="tablewrap"><table><tbody>{JSON.parse(view.lines).map((l:any)=><tr key={l.id}><td>{l.code}</td><td>{l.qty} × {unit(l.unit)}</td><td>{money(l.price*l.qty)}</td></tr>)}</tbody></table></div><p>{view.notes}</p><strong>Subtotal {money(view.subtotal)}</strong><div className="stackbuttons"><button disabled={busy} onClick={()=>action('order-status',{id:view.id,status:'in_review'})}>Mark in review</button><button disabled={busy} onClick={()=>action('order-status',{id:view.id,status:'approved'})}>Approve for office invoicing</button></div><p className="hint">Approval does not create a QuickBooks invoice or charge a customer.</p></>}</DialogContent></Dialog>
</>;
}
